// <auto-generated />
namespace PlutoWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OtherLookUpTbls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OtherLookUpTbls));
        
        string IMigrationMetadata.Id
        {
            get { return "201711202035289_OtherLookUpTbls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
